---
- hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - name: Actualizar cache de APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalar herramientas de sistema y diseño
      apt:
        name:
          - curl
          - htop
          - figlet
        state: present

    - name: Crear banner de bienvenida con figlet
      shell: "figlet 'DCSolutions SRL' > /etc/motd"
      args:
        creates: /etc/motd_custom_done # Esto evita que se ejecute innecesariamente cada vez

    - name: Generar archivo de confirmacion final
      copy:
        content: "Equipo actualizado con figlet el {{ ansible_date_time.iso8601 }}"
        dest: /tmp/ansible_figlet_ok.txt
